export const GET_WALLETS_REQUEST = "GET_WALLETS_REQUEST";
export const GET_WALLETS_REQUEST_SUCCESS = "GET_WALLETS_REQUEST_SUCCESS";
export const PUT_WALLETS_REQUEST = "PUT_WALLETS_REQUEST";
export const DELETE_WALLET_REQUEST = "DELETE_WALLET_REQUEST";

export const GET_COLLECTION_STATS_REQUEST = "GET_COLLECTION_STATS_REQUEST";
export const GET_COLLECTION_STATS_REQUEST_SUCCESS =
  "GET_COLLECTION_STATS_REQUEST_SUCCESS";
